
```{r}
library(dplyr)
library(Seurat)
library(patchwork)
library(readr)
library(cols4all)
library(openxlsx)
library(tibble)
library(ggplot2)
```

##load data
```{r}
sobj<-sobj
```
##calculate mt
```{r}

```


```{r}
sobj$percent.mt <- PercentageFeatureSet(sobj, pattern = "^mt-")
summary(sobj$percent.mt)
#鼠使用mt

samplelist<-levels(sobj$orig.ident)
# Meta.X <- sobj@meta.data %>%
#   rownames_to_column(var = "barcodes")
```



##plot.mt
```{r}
for (sample in samplelist) {
  
  dataplot<-Meta.X %>%
    filter(orig.ident==sample)
  Density_mt<-ggplot(dataplot, aes(x=percent.mt, fill=orig.ident)) +
  geom_density()+
  ylim(0,4)+
  xlim(0,3)
  ggsave(filename = paste0("../plot/mt/",sample,"_Density_mt.png"),plot = Density_mt,device = "png",width=3000,height = 2000,dpi = 300,units = "px")
}

  Density_mt<-ggplot(Meta.X, aes(x=percent.mt, fill=orig.ident)) +
  geom_density()+
  ylim(0,3)+
  xlim(0,3)
  ggsave(filename = paste0("../plot/mt/","_Density_mt.png"),plot = Density_mt,device = "png",width=3000,height = 2000,dpi = 300,units = "px")
```

```{r}
summary(sobj$percent.mt)
```


##plot.nFeature
```{r}
for (sample in samplelist) {
  
  dataplot<-Meta.X %>%
    filter(orig.ident==sample)
  Density_mt<-ggplot(dataplot, aes(x=nFeature_RNA, fill=orig.ident)) +
  geom_density()
  ggsave(filename = paste0("../plot/feature/",sample,"_Density_feature.png"),plot = Density_mt,device = "png",width=3000,height = 2000,dpi = 300,units = "px")
}

  Density_mt<-ggplot(Meta.X, aes(x=nFeature_RNA, fill=orig.ident)) +
  geom_density()
  ggsave(filename = paste0("../plot/feature/","_Density_feature.png"),plot = Density_mt,device = "png",width=3000,height = 2000,dpi = 300,units = "px")
```
##plot.nCount


```{r}
summary(sobj$nCount_RNA)
table(sobj$orig.ident)
summary(sobj$nFeature_RNA)

```

```{r}

for (sample in samplelist) {
  
  dataplot<-Meta.X %>%
    filter(orig.ident==sample)
  Density_mt<-ggplot(dataplot, aes(x=nCount_RNA, fill=orig.ident)) +
  geom_density()+
    ylim(0,0.00025)
  ggsave(filename = paste0("../plot/count/",sample,"_Density_count.png"),plot = Density_mt,device = "png",width=3000,height = 2000,dpi = 300,units = "px")
}

  Density_mt<-ggplot(Meta.X, aes(x=nCount_RNA, fill=orig.ident)) +
  geom_density()
  ggsave(filename = paste0("../plot/count/","_Density_count.png"),plot = Density_mt,device = "png",width=3000,height = 2000,dpi = 300,units = "px")
```
  
##calculate decrease rate
```{r}
sobj.filtered <- subset(sobj, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 5)
sobj
sobj.filtered
```

```{r}

```

```{r}
table(sobj$orig.ident)
table(sobj.filtered$orig.ident)
QCnumber<-cbind(table(sobj$orig.ident),table(sobj.filtered$orig.ident)) %>%as.data.frame
names(QCnumber)<-c("before_QC","after_QC")

QCnumber<-QCnumber %>%
  mutate(percentagecut=(after_QC-before_QC)/before_QC *100)
write.csv(QCnumber,"../Documents/QCnumber_mt300.csv")
```